### ISSUE TITLE
关于对比方法

### ISSUE THREAD

**Issue by touchthefish233** [Leeiieeo/AG-Pose#1]
请问为什么没有和很多新的文章做对比？ 23-cvpr hs pose ； 23年iccv ist-net， SOCS ； 23年neurips genPose ； 这些文章早在cvpr投稿之前就开完会了

**Comment by touchthefish233** [comment]
还有一个问题，NOCS数据集中，只有camera有较大的形状变化， 文章也着重强调有利于形状变化大的instance， 如果能给出camera类别的精度指标，就更有说服力了

**Comment by touchthefish233** [comment]
请问，文章是端到端的方法吗？端到端的方法大多有过拟合的问题，wild6d数据集常见于之前的工作中，本文方法有在wild6d上测试的结果吗？

**Comment by Leeiieeo** [comment]
> 还有一个问题，NOCS数据集中，只有camera有较大的形状变化， 文章也着重强调有利于形状变化大的instance， 如果能给出camera类别的精度指标，就更有说服力了

谢谢你的建议。事实上我们在rebuttal的过程中已经在一个更大的数据集HOUSECAT6D上进行了实验并验证了方法的有效性，但是实验结果并没有放在cvpr camera-ready的正文里，我们后续会在这个repo以及可能的扩展版本中完整的加上这部分的内容。

| Method     | IoU_25| IoU_50 |
| ----------- | ----------- |---------|
| NOCS    | 50.0|21.2|
| GPV-Pose  | 74.9        |50.7|
| VI-Net  | 80.7        |56.4|
| AG-Pose  | 83.2        |68.3|

**Comment by Leeiieeo** [comment]
> 请问，文章是端到端的方法吗？端到端的方法大多有过拟合的问题，wild6d数据集常见于之前的工作中，本文方法有在wild6d上测试的结果吗？

我们并没有在wild6D上进行实验，因为这个数据集更适合半监督的方法。

**Comment by Leeiieeo** [comment]
> 请问为什么没有和很多新的文章做对比？ 23-cvpr hs pose ； 23年iccv ist-net， SOCS ； 23年neurips genPose ； 这些文章早在cvpr投稿之前就开完会了

谢谢你的建议。我们在正文中已经尽可能的包含当前的sota方法了，但可能出于疏忽漏掉了一些工作，我们会在可能的后续的扩展版本中完善这部分内容。

**Comment by touchthefish233** [comment]
非常感谢您及时的回复，您的回复非常具有说服力。

**Comment by touchthefish233** [comment]
请问您方便提供一下，NOCS 数据集上，camera这个类上，各项的指标吗

**Comment by touchthefish233** [comment]
十分确信您做了一个出色的工作！

**Comment by Leeiieeo** [comment]
> 请问您方便提供一下，NOCS 数据集上，camera这个类上，各项的指标吗

感谢你的关注。你可以通过[Supplementary Material](http://home.ustc.edu.cn/~llinxiao/supp.pdf)了解到这部分内容以及其他有关的实验。
