### ISSUE TITLE
关于计算3D IOU计算

### ISSUE THREAD

**Issue by Alanwaker** [Leeiieeo/AG-Pose#16]
![image](https://github.com/user-attachments/assets/d2e58632-9ba4-4fe7-bb14-afef2d2fd067)
我看见了备注的# new这四行，怎么说呢，我觉得这四行更合理一些（从2D IOU计算类比），但是看了其他代码也是采用的axis=0,第一种方法。我有点不太能理解，能帮忙解答一下吗？谢谢

**Comment by Leeiieeo** [comment]
这有点像一个遗留问题，可能最早的某个仓库的代码错了但是被沿用了。我们的代码里分别有原始的3DIOU和[CATRE](https://github.com/THU-DA-6D-Pose-Group/CATRE)的指标，前者可以和别的之前的方法比较，后者是比较合理的指标也有很多比较新的paper在用

**Comment by Alanwaker** [comment]
好的，非常感谢！
