### ISSUE TITLE
warning no valid point

### ISSUE THREAD

**Issue by AFESDTTM** [Leeiieeo/AG-Pose#3]
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/ecf42a04-fd9d-4f47-bc68-c6c23e871517)
你好，我想问一下，在训练的时候出先warning no valid point是什么意思，我是把模型下载到本地的。
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/d779f709-be53-4d96-8d93-efe92edae43b)
是不是我模型下载错了，还是什么原因？

**Comment by AFESDTTM** [comment]
而且没有吃GPU
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/c1f6b73d-4234-42dc-b4b7-f965519c23ee)

**Comment by Leeiieeo** [comment]
您好，出现warning no valid point的原因在[这里](https://github.com/Leeiieeo/AG-Pose/blob/232fee5f6e454f96131eede5c421fd113c423e06/model/Net.py#L172)，可能是数据集本身标注的误差产生的，正常训练忽略即可。

关于没有占用GPU的原因我也不是很确定产生的原因，您是直接运行的```python train.py --config config/REAL/camera_real.yaml```吗？可能可以通过指定GPU序号解决，例如指定0号GPU，```python train.py --config config/REAL/camera_real.yaml --gpus 0```

有什么问题可以继续沟通

**Comment by Leeiieeo** [comment]
另外如果显存不够的话可以调整config文件中的batchsize

**Comment by AFESDTTM** [comment]
好的谢谢您，我再去尝试一下

**Comment by AFESDTTM** [comment]
你好，我发现我指定用第1,2块卡跑它实际是用的第0块，你知道是什么原因吗，或者代码那地方需要改动呢
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/49e3e787-57f3-4ff8-b768-627a5c8caf80)

**Comment by Leeiieeo** [comment]
您好，我们并没有进行多卡的测试，我们的结果都是在单张24G的3090上的结果。如果你显存不够的话可以调整[config](https://github.com/Leeiieeo/AG-Pose/blob/232fee5f6e454f96131eede5c421fd113c423e06/config/REAL/camera_real.yaml#L10-L11)中的```syn_bs, real_bs```，按照3：1的比例调小一些结果应该不会有很大的差距

**Comment by AFESDTTM** [comment]
好的，谢谢您

**Comment by Leeiieeo** [comment]
欢迎您在这里展示您的实验结果，这样我可以聊到到我们实验在其他机器上的可复现性。

**Comment by AFESDTTM** [comment]
您好，我想问问，在3090上训练一个epoch大概需要多久

**Comment by Leeiieeo** [comment]
我们在NOCS上训练30个epoch大概需要25h，可以下载我们的[log](http://home.ustc.edu.cn/~llinxiao/log.zip)查看。

**Comment by AFESDTTM** [comment]
我想请问一下，如何训练测试CAMERA数据集呢

**Comment by AFESDTTM** [comment]
是不是只要训练NOCS,然后直接测试REAL和CAMERA

**Comment by Leeiieeo** [comment]
根据我们的测试结果来看，不管训练集是CAMERA还是CAMERA+REAL，在CAMERA测试集上的结果没有太大区别。我们提供的[ckpt](http://home.ustc.edu.cn/~llinxiao/log.zip)是在NOCS上一起训练的，然后分布在REAL和CAMERA上做测试的

**Comment by AFESDTTM** [comment]
好的，谢谢您的回复

**Comment by AFESDTTM** [comment]
是只修改吗
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/08004d85-b339-44c5-985c-01c1b20cbd46)
我修改进行测试显示的
![image](https://github.com/Leeiieeo/AG-Pose/assets/106895081/474fd716-5875-4639-8d70-b3fcaffb0e3a)

**Comment by Leeiieeo** [comment]
您好，我测试刚刚测试了一下是可以的。这个warning是[这里](https://github.com/Leeiieeo/AG-Pose/blob/232fee5f6e454f96131eede5c421fd113c423e06/utils/data_utils.py#L260)产生的，可能是你的数据集存放位置和我不一致，可以debug排查一下。

**Comment by zxl55552** [comment]
你好，请问测试camera数据集成功了吗

**Comment by AFESDTTM** [comment]
> 你好，请问测试相机数据集吗？
咱们的数据集中的深度图名称与作者的不一致

**Comment by AFESDTTM** [comment]
> 你好，请问相机数据集？

我们的数据集中的深度图的名称与作者代码中的不一致造成的

**Comment by zxl55552** [comment]
您好，请问你测试camera数据集成功了吗？你下载的数据集是作者主页里的链接的数据集吗？我得到了一些报错
Test [717/19220][5]: : 4%|████▉ | 717/19220 [00:27<10:34, 29.18it/s]warning: No data
Test [846/19220][1]: : 4%|█████▊ | 845/19220 [00:31<10:24, 29.41it/s]warning: No data
Test [922/19220][3]: : 5%|██████▎ | 921/19220 [00:34<09:58, 30.56it/s]libpng error: IDAT: CRC error
Test [938/19220][3]: : 5%|██████▍ | 938/19220 [00:35<11:22, 26.80it/s]
Traceback (most recent call last):
File "/root/autodl-tmp/AG-Pose-main/test.py", line 114, in
test_func(model, dataloder, save_path)
File "/root/autodl-tmp/AG-Pose-main/utils/solver.py", line 225, in test_func
for i, data in enumerate(dataloder):
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in next
data = self._next_data()
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data
return self._process_data(data)
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data
data.reraise()
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise
raise exception
TypeError: Caught TypeError in DataLoader worker process 2.
Original Traceback (most recent call last):
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
data = fetcher.fetch(index)
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/autodl-tmp/AG-Pose-main/provider/nocs_dataset.py", line 210, in getitem
rgb = cv2.imread(image_path + '_color.png')[:, :, :3]
TypeError: 'NoneType' object is not subscriptable。  请问你遇到过这些问题吗

**Comment by AFESDTTM** [comment]
> 您好，请问你测试camera数据集成功了吗？你下载的数据集是作者主页里的链接的数据集吗？我得到了一些报错 Test [717/19220][5]: : 4%|████▉ | 717/19220 [00:27<10:34, 29.18it/s]warning: No data Test [846/19220][1]: : 4%|█████▊ | 845/19220 [00:31<10:24, 29.41it/s]warning: No data Test [922/19220][3]: : 5%|██████▎ | 921/19220 [00:34<09:58, 30.56it/s]libpng error: IDAT: CRC error Test [938/19220][3]: : 5%|██████▍ | 938/19220 [00:35<11:22, 26.80it/s] Traceback (most recent call last): File "/root/autodl-tmp/AG-Pose-main/test.py", line 114, in test_func(model, dataloder, save_path) File "/root/autodl-tmp/AG-Pose-main/utils/solver.py", line 225, in test_func for i, data in enumerate(dataloder): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in next data = self._next_data() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data return self._process_data(data) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data data.reraise() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise raise exception TypeError: Caught TypeError in DataLoader worker process 2. Original Traceback (most recent call last): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/AG-Pose-main/provider/nocs_dataset.py", line 210, in getitem rgb = cv2.imread(image_path + '_color.png')[:, :, :3] TypeError: 'NoneType' object is not subscriptable。 请问你遇到过这些问题吗

没有遇到过，我是从DPDN中下载的，下载完需要进行预处理，DPDN中的预处理代码

**Comment by zxl55552** [comment]
是data_processing.py文件吧，我已经预处理完了，测试real数据集是正常的，但是camera数据集就报上述错误


---- Replied Message ----
| From | ***@***.***> |
| Date | 06/20/2024 15:12 |
| To | Leeiieeo/AG-Pose ***@***.***> |
| Cc | zxl55552 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [Leeiieeo/AG-Pose] warning no valid point (Issue #3) |

您好，请问你测试camera数据集成功了吗？你下载的数据集是作者主页里的链接的数据集吗？我得到了一些报错 Test [717/19220][5]: : 4%|████▉ | 717/19220 [00:27<10:34, 29.18it/s]warning: No data Test [846/19220][1]: : 4%|█████▊ | 845/19220 [00:31<10:24, 29.41it/s]warning: No data Test [922/19220][3]: : 5%|██████▎ | 921/19220 [00:34<09:58, 30.56it/s]libpng error: IDAT: CRC error Test [938/19220][3]: : 5%|██████▍ | 938/19220 [00:35<11:22, 26.80it/s] Traceback (most recent call last): File "/root/autodl-tmp/AG-Pose-main/test.py", line 114, in test_func(model, dataloder, save_path) File "/root/autodl-tmp/AG-Pose-main/utils/solver.py", line 225, in test_func for i, data in enumerate(dataloder): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in next data = self._next_data() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data return self._process_data(data) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data data.reraise() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise raise exception TypeError: Caught TypeError in DataLoader worker process 2. Original Traceback (most recent call last): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/AG-Pose-main/provider/nocs_dataset.py", line 210, in getitem rgb = cv2.imread(image_path + '_color.png')[:, :, :3] TypeError: 'NoneType' object is not subscriptable。 请问你遇到过这些问题吗

没有遇到过，我是从DPDN中下载的，下载完需要进行预处理，DPDN中的预处理代码

**Comment by zxl55552** [comment]
你好，请问你测试camera数据集和原论文中的结果差别大吗？测试的时候有没有出现no data的情况

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/20/2024 15:12 |
| To | Leeiieeo/AG-Pose ***@***.***> |
| Cc | zxl55552 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [Leeiieeo/AG-Pose] warning no valid point (Issue #3) |

您好，请问你测试camera数据集成功了吗？你下载的数据集是作者主页里的链接的数据集吗？我得到了一些报错 Test [717/19220][5]: : 4%|████▉ | 717/19220 [00:27<10:34, 29.18it/s]warning: No data Test [846/19220][1]: : 4%|█████▊ | 845/19220 [00:31<10:24, 29.41it/s]warning: No data Test [922/19220][3]: : 5%|██████▎ | 921/19220 [00:34<09:58, 30.56it/s]libpng error: IDAT: CRC error Test [938/19220][3]: : 5%|██████▍ | 938/19220 [00:35<11:22, 26.80it/s] Traceback (most recent call last): File "/root/autodl-tmp/AG-Pose-main/test.py", line 114, in test_func(model, dataloder, save_path) File "/root/autodl-tmp/AG-Pose-main/utils/solver.py", line 225, in test_func for i, data in enumerate(dataloder): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in next data = self._next_data() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data return self._process_data(data) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data data.reraise() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise raise exception TypeError: Caught TypeError in DataLoader worker process 2. Original Traceback (most recent call last): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/AG-Pose-main/provider/nocs_dataset.py", line 210, in getitem rgb = cv2.imread(image_path + '_color.png')[:, :, :3] TypeError: 'NoneType' object is not subscriptable。 请问你遇到过这些问题吗

没有遇到过，我是从DPDN中下载的，下载完需要进行预处理，DPDN中的预处理代码

**Comment by AFESDTTM** [comment]
> 你好，请问你测试camera数据集和原论文中的结果差别大吗？测试的时候有没有出现no data的情况
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 06/20/2024 15:12 | | To | Leeiieeo/AG-Pose ***@***.***> | | Cc | zxl55552 ***@***.***>, Comment ***@***.***> | | Subject | Re: [Leeiieeo/AG-Pose] warning no valid point (Issue #3) | 您好，请问你测试camera数据集成功了吗？你下载的数据集是作者主页里的链接的数据集吗？我得到了一些报错 Test [717/19220][5]: : 4%|████▉ | 717/19220 [00:27<10:34, 29.18it/s]warning: No data Test [846/19220][1]: : 4%|█████▊ | 845/19220 [00:31<10:24, 29.41it/s]warning: No data Test [922/19220][3]: : 5%|██████▎ | 921/19220 [00:34<09:58, 30.56it/s]libpng error: IDAT: CRC error Test [938/19220][3]: : 5%|██████▍ | 938/19220 [00:35<11:22, 26.80it/s] Traceback (most recent call last): File "/root/autodl-tmp/AG-Pose-main/test.py", line 114, in test_func(model, dataloder, save_path) File "/root/autodl-tmp/AG-Pose-main/utils/solver.py", line 225, in test_func for i, data in enumerate(dataloder): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in next data = self._next_data() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1356, in _next_data return self._process_data(data) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1402, in _process_data data.reraise() File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/_utils.py", line 461, in reraise raise exception TypeError: Caught TypeError in DataLoader worker process 2. Original Traceback (most recent call last): File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop data = fetcher.fetch(index) File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/miniconda3/envs/ag/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/root/autodl-tmp/AG-Pose-main/provider/nocs_dataset.py", line 210, in getitem rgb = cv2.imread(image_path + '_color.png')[:, :, :3] TypeError: 'NoneType' object is not subscriptable。 请问你遇到过这些问题吗 没有遇到过，我是从DPDN中下载的，下载完需要进行预处理，DPDN中的预处理代码 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我出现no data的情况的处理后的深度图，与作者代码中的Camera深度图名称不一致造成的，我测试camera数据稍微低了4个点，可是导入模型的问题

**Comment by Leeiieeo** [comment]
https://github.com/Leeiieeo/AG-Pose/issues/11#issuecomment-2181848287

**Comment by AFESDTTM** [comment]
> 同一个实验先后测试REAL和CAMERA数据集需要注意 [#11 (comment)](https://github.com/Leeiieeo/AG-Pose/issues/11#issuecomment-2181848287)

好的，谢谢你的帮助
