### ISSUE TITLE
about results visualization

### ISSUE THREAD

**Issue by 7-Ryan** [Leeiieeo/AG-Pose#4]
Hello, in the code you released, I find the draw_utils.py, but I can't find the code part that uses it, can you share the code of the visual part of your results detection? Or where can I find it if needed? NOCS?
Thank you very much!

**Comment by Leeiieeo** [comment]
Hi, I have released the code for visualization [here](https://github.com/Leeiieeo/AG-Pose?tab=readme-ov-file#visualization).

Let me know if you need further help.
