### ISSUE TITLE
Can you answer my questions?

### ISSUE THREAD

**Issue by dj1367250510** [Leeiieeo/AG-Pose#5]
Hi, I would like to ask why the results in the logs you provided are higher than the results in your paper?

**Comment by Leeiieeo** [comment]
Hi, this repo is the code for the extended version of our CVPR24 paper. We made further optimization and provide more results on HouseCat6D dataset. 

You can see the main modification [here](https://github.com/Leeiieeo/AG-Pose?tab=readme-ov-file#ag-pose-instance-adaptive-and-geometric-aware-keypoint-learning-for-category-level-6d-object-pose-estimation).

**Comment by dj1367250510** [comment]
Thank you for your reply.
