### ISSUE TITLE
OOM问题

### ISSUE THREAD

**Issue by 807448346** [Leeiieeo/AG-Pose#9]
你好，当我在服务器上运行训练脚本时，指定GPU运行却仍然报OOM错误，如图
![image](https://github.com/Leeiieeo/AG-Pose/assets/76234881/06eb3569-06d6-45a7-9d67-3f31fd8da3d1)
![image](https://github.com/Leeiieeo/AG-Pose/assets/76234881/9ea331d3-314d-4aeb-b03f-789194e4a0cf)
参照网络上的方法我已经将batch_size缩到很小，又或者调整了pin_memory，又进行了cache清理的操作，但是这些方法均起不到任何作用，请问这种该如何解决呢？

**Comment by 807448346** [comment]
`python train.py --config config/REAL/camera_real.yaml --gpus 2`我执行的命令

**Comment by 807448346** [comment]
> 看起来似乎只是在初始化网络参数的时候就OOM了，还没有进行到读取数据进行网络forward的过程。抱歉我也没有遇到过这样的情况

您好，我搜索了某些论坛，有人说是因为torch与cuda版本和系统不匹配的问题，并给出了两行测试代码的python文件。如下图所示
![image](https://github.com/Leeiieeo/AG-Pose/assets/76234881/c7bd3ac4-e186-4fcb-b593-f4c966e284c8)
当我运行这两行代码的py文件时仍然出现了OOM错误，但当我检查版本时，我的torch对应的cuda版本与系统的cuda版本是一致的，期间我也安装过torch12.0与12.1但是都无法解决OOM，您有什么想法吗？
![image](https://github.com/Leeiieeo/AG-Pose/assets/76234881/7b2081ad-53fc-44b7-8884-e95192f42d12)
![image](https://github.com/Leeiieeo/AG-Pose/assets/76234881/9e781555-51b6-438c-a728-5554e1e03eb6)

**Comment by wh631q** [comment]
请问问题解决了吗

**Comment by 807448346** [comment]
> 请问问题解决了吗

已经解决了，回退torch版本了
